@startuml
title Animal 추상화 구조

abstract class Animal {
  - name : String
  --
  + Animal(name:String)
  + showName() : void
  + sound() : void
  + move() : void
}

class Dog {
  + Dog(name:String)
  + sound() : void
  + move() : void
}

class Cat {
  + Cat(name:String)
  + sound() : void
  + move() : void
}

class Bird {
  + Bird(name:String)
  + sound() : void
  + move() : void
}

Animal <|-- Dog
Animal <|-- Cat
Animal <|-- Bird
@enduml
